routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('dashboard');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

Route::group(['prefix' => 'master-data'], function () {
    Route::resource('/employee', 'EmployeeController')->middleware('auth');

    //position route
    Route::resource('/position', 'PositionController')->middleware('auth');
    Route::get('/position/get-indicator/{position_id}', 'PositionController@GetIndicator')->middleware('auth')->name('position.add_indicator');
    Route::post('/position/add-indicator', 'PositionController@AddIndicator')->middleware('auth')->name('position.addIndicator.post');
    Route::delete('position/delete-indicator/{indicator_id}', 'PositionController@DeleteIndicator')->middleware('auth')->name('position.deleteIndicator');
    Route::get('/position/{position_id}/params_data', 'AssessmentController@IndexParamsData')->name('position.indexparamsdata');

    Route::resource('/indicator', 'IndicatorController')->middleware('auth');
    Route::get('/indicator/get-proxy/{indicator_id}', 'IndicatorController@GetProxy')->middleware('auth')->name('indicator.add_proxy');
    Route::post('/indicator/add-proxy/', 'IndicatorController@AddProxy')->middleware('auth')->name('indicator.addProxy.post');
    Route::delete('indicator/delete-proxy/{proxy_id}', 'IndicatorController@DeleteProxy')->middleware('auth')->name('indicator.deleteProxy');

    // Route::resource('/job', 'JobController')->middleware('auth');
    Route::resource('/proxy', 'ProxyController')->middleware('auth');
    Route::resource('/subproxy', 'SubProxyController')->middleware('auth');

    //satuan route
    Route::resource('/satuan', 'SatuanController')->middleware('auth');


});

Route::group(['prefix' => 'assessment','middleware' => 'auth'], function () {
    Route::get('/employee', 'AssessmentController@Employee')->name('assessment.employee');
    //indicator
    Route::post('/indicator/save', 'AssessmentController@IndicatorSave')->name('assessment.indicator.save');
    Route::post('/indicator/update/{indicator_id}', 'AssessmentController@IndicatorUpdate')->name('assessment.indicator.update');
    Route::get('/indicator/get/{indicator_id}', 'AssessmentController@GetIndicator')->name('assessment.indicator.get');
    Route::get('/indicator/delete/{indicator_id}','AssessmentController@IndicatorDelete')->name('assessment.indicator.delete');

    //proxy
    Route::post('/proxy/save', 'AssessmentController@ProxySave')->name('assessment.proxy.save');
    Route::post('/proxy/update/{proxy_id}', 'AssessmentController@ProxyUpdate')->name('assessment.proxy.update');
    Route::get('/proxy/get/{proxy_id}', 'AssessmentController@GetProxy')->name('assessment.proxy.get');
    Route::get('/proxy/delete/{proxy_id}','AssessmentController@ProxyDelete')->name('assessment.proxy.delete');

    //subproxy
    Route::post('/subproxy/save', 'AssessmentController@SubProxySave')->name('assessment.subproxy.save');
    Route::post('/subproxy/update/{subproxy_id}', 'AssessmentController@SubProxyUpdate')->name('assessment.subproxy.update');
    Route::get('/subproxy/get/{subproxy_id}', 'AssessmentController@GetSubProxy')->name('assessment.subproxy.get');
    Route::get('/subproxy/delete/{subproxy_id}','AssessmentController@SubProxyDelete')->name('assessment.subproxy.delete');
    Route::post('/subproxy/rumus/save', 'AssessmentController@AddRumus')->name('assessment.subproxy.rumus.add');
    Route::get('/subproxy/rumus/get/{proxy_id}', 'AssessmentController@GetRumus')->name('assessment.subproxy.rumus.get');


});

Route::group(['prefix' => 'calculate','middleware' => 'auth'], function () {
    Route::get('/employee/{employee_id}', 'CalculateController@index')->name('calculate.index');
    Route::post('/subproxy', 'CalculateController@CalculateSubproxy')->name('calculate.subproxy');
});

Route::group(['prefix' => 'recap','middleware' => 'auth'], function () {
    Route::get('/', 'RecapController@index')->name('recap.index');
    Route::post('/save', 'RecapController@store')->name('recap.store');
    Route::get('/get-report/{from}/{to}/{employee_id}', 'RecapController@report')->name('recap.report');
});

app/Proxy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Proxy extends Model
{
    protected $fillable = [
        'name','bobot','indicator_id','user_id','satuan_id','target'
    ];

    public function scopeUserLogin($query)
    {
        return $query->where('user_id', user_login()->id);
    }

    public function indicator()
    {
        return $this->hasOne('App\Indicator', 'id', 'indicator_id');
    }

    public function subproxies()
    {
        return $this->hasMany('App\SubProxy', 'proxy_id', 'id');
    }
    
    public function rumuss()
    {
        return $this->hasOne('App\RumusSubProxy', 'proxy_id', 'id');
    }

    public function satuan()
    {
        return $this->hasOne('App\Satuan', 'id', 'satuan_id');
    }
}

app/Http/Controllers/ProxyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Proxy\ProxyRequest;
use App\Proxy;
use App\Indicator;


class ProxyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $proxies = Proxy::userLogin()->get();
        return view('admin.proxy.index', compact('proxies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $indicators = Indicator::userLogin()->get();
        return view('admin.proxy.form', compact('indicators'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProxyRequest $request)
    {
        try {
            $save = Proxy::create([
                // 'indicator_id' => $request->indicator_id,
                'name' => $request->name,
                // 'bobot' => $request->bobot,
                'user_id' => user_login()->id,
            ]);    

            return redirect(route('proxy.index'));
        } catch (\Throwable $th) {
            return $th->getMessage();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $indicators = Indicator::userLogin()->get();
        $proxy = Proxy::findOrFail($id);
        return view('admin.proxy.form', compact('proxy','indicators'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProxyRequest $request, $id)
    {
        try {
            $proxy = Proxy::findOrFail($id);
            // $proxy->indicator_id = $request->indicator_id;    
            $proxy->name = $request->name;    
            // $proxy->bobot = $request->bobot; 
            $proxy->user_id = user_login()->id;
            $proxy->save();
            
            return redirect(route('proxy.index'));
        } catch (\Throwable $th) {
            return $th->getMessage();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            Proxy::destroy($id);

            return redirect(route('proxy.index'));
        } catch (\Throwable $th) {
            return $th->getMessage();
        }
    }
}

resources/views/admin/proxy/css.blade.php
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('assets') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="{{ asset('assets') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <link rel="stylesheet" href="{{ asset('assets') }}/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

resources/views/admin/proxy/form.blade.php
@extends('layouts.main_app')
@push('css')
@include('admin.proxy.css')
@endpush
@push('script')
@include('admin.proxy.script')
@endpush
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Proxy</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Master Data</a></li>
                    <li class="breadcrumb-item active">Proxy</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Form Proxy</h3>
                    </div>
                    @php
                        $url = route('proxy.store');
                        if (!empty($proxy)) {
                            $url = route('proxy.update',$proxy->id);
                        }
                    @endphp
                    <form action="{{ $url }}" method="POST">
                        @csrf
                        @if (!empty($proxy))
                            @method('PUT')
                        @endif
                        <div class="card-body">
                            {{--  <div class="form-group">
                                <label for="name">Indikator</label>
                                <select name="indicator_id" id="indicator_id" class="form-control" required>
                                    <option value="">-- Pilih Indikator --</option>
                                    @foreach ($indicators as $indicator)
                                        <option value="{{ $indicator->id }}" @if (@$indicator->id == @$proxy->indicator_id) selected @endif>{{ $indicator->name }}</option>
                                    @endforeach
                                </select>
                            </div>  --}}
                            <div class="form-group">
                                <label for="name">Nama Proxy</label>
                                <input type="text" class="form-control" id="name" placeholder="Masukkan nama" name="name" required value="{{ @$proxy->name }}">
                            </div>
                            {{--  <div class="form-group">
                                <label for="bobot">Bobot Proxy</label>
                                <div class="input-group mb-3">
                                    <input type="number" class="form-control col-md-4" name="bobot" required value="{{ @$proxy->bobot }}">
                                    <div class="input-group-append">
                                      <span class="input-group-text"><i class="fa fa-percent"></i></span>
                                    </div>
                                </div>
                            </div>  --}}
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">SAVE</button>
                        </div>
                    </form>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

resources/views/admin/proxy/index.blade.php
@extends('layouts.main_app')
@push('css')
@include('admin.proxy.css')
@endpush
@push('script')
@include('admin.proxy.script')
@endpush
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Proxy</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Master Data</a></li>
                    <li class="breadcrumb-item active">Proxy</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="text-right">
                            <a href="{{ route('proxy.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah Proxy</a>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Nama Proxy</th>
                                    <th>Sub Proxy</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($proxies as $proxy)
                                    <tr>
                                        <td>{{ $proxy->name }}</td>
                                        <td>
                                            <ul>
                                            @foreach ($proxy->subproxies as $subproxy)
                                                <li>{{ $subproxy->name }} ({{ $subproxy->code }})</li>
                                            @endforeach
                                            </ul>
                                        </td>
                                        <td>
                                            <div class="row">
                                                <a href="{{ route('proxy.edit',$proxy->id) }}" class="btn btn-warning btn-sm mr-1"><i class="fa fa-edit"></i></a>
                                                <form action="{{ route('proxy.destroy', $proxy->id) }}" method="POST">@csrf @method('DELETE')  <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('apakah anda yakin ?')"><i class="fa fa-trash"></i></button> </form>
                                                <a href="" class="btn btn-primary btn-sm ml-1">Sub Proxy</a>
                                            </div>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="3">Data no found</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

resources/views/admin/proxy/script.blade.php
<!-- DataTables  & Plugins -->
<script src="{{ asset('assets') }}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="{{ asset('assets') }}/plugins/jszip/jszip.min.js"></script>
<script src="{{ asset('assets') }}/plugins/pdfmake/pdfmake.min.js"></script>
<script src="{{ asset('assets') }}/plugins/pdfmake/vfs_fonts.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

<script>
    $(function () {
        $("#example1").DataTable({
            "responsive": true, "lengthChange": false, "autoWidth": false,
            "buttons": ["csv", "excel", "pdf", "print"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    });
</script>