routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('dashboard');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

Route::group(['prefix' => 'master-data'], function () {
    Route::resource('/employee', 'EmployeeController')->middleware('auth');

    //position route
    Route::resource('/position', 'PositionController')->middleware('auth');
    Route::get('/position/get-indicator/{position_id}', 'PositionController@GetIndicator')->middleware('auth')->name('position.add_indicator');
    Route::post('/position/add-indicator', 'PositionController@AddIndicator')->middleware('auth')->name('position.addIndicator.post');
    Route::delete('position/delete-indicator/{indicator_id}', 'PositionController@DeleteIndicator')->middleware('auth')->name('position.deleteIndicator');
    Route::get('/position/{position_id}/params_data', 'AssessmentController@IndexParamsData')->name('position.indexparamsdata');

    Route::resource('/indicator', 'IndicatorController')->middleware('auth');
    Route::get('/indicator/get-proxy/{indicator_id}', 'IndicatorController@GetProxy')->middleware('auth')->name('indicator.add_proxy');
    Route::post('/indicator/add-proxy/', 'IndicatorController@AddProxy')->middleware('auth')->name('indicator.addProxy.post');
    Route::delete('indicator/delete-proxy/{proxy_id}', 'IndicatorController@DeleteProxy')->middleware('auth')->name('indicator.deleteProxy');

    // Route::resource('/job', 'JobController')->middleware('auth');
    Route::resource('/proxy', 'ProxyController')->middleware('auth');
    Route::resource('/subproxy', 'SubProxyController')->middleware('auth');

    //satuan route
    Route::resource('/satuan', 'SatuanController')->middleware('auth');


});

Route::group(['prefix' => 'assessment','middleware' => 'auth'], function () {
    Route::get('/employee', 'AssessmentController@Employee')->name('assessment.employee');
    //indicator
    Route::post('/indicator/save', 'AssessmentController@IndicatorSave')->name('assessment.indicator.save');
    Route::post('/indicator/update/{indicator_id}', 'AssessmentController@IndicatorUpdate')->name('assessment.indicator.update');
    Route::get('/indicator/get/{indicator_id}', 'AssessmentController@GetIndicator')->name('assessment.indicator.get');
    Route::get('/indicator/delete/{indicator_id}','AssessmentController@IndicatorDelete')->name('assessment.indicator.delete');

    //proxy
    Route::post('/proxy/save', 'AssessmentController@ProxySave')->name('assessment.proxy.save');
    Route::post('/proxy/update/{proxy_id}', 'AssessmentController@ProxyUpdate')->name('assessment.proxy.update');
    Route::get('/proxy/get/{proxy_id}', 'AssessmentController@GetProxy')->name('assessment.proxy.get');
    Route::get('/proxy/delete/{proxy_id}','AssessmentController@ProxyDelete')->name('assessment.proxy.delete');

    //subproxy
    Route::post('/subproxy/save', 'AssessmentController@SubProxySave')->name('assessment.subproxy.save');
    Route::post('/subproxy/update/{subproxy_id}', 'AssessmentController@SubProxyUpdate')->name('assessment.subproxy.update');
    Route::get('/subproxy/get/{subproxy_id}', 'AssessmentController@GetSubProxy')->name('assessment.subproxy.get');
    Route::get('/subproxy/delete/{subproxy_id}','AssessmentController@SubProxyDelete')->name('assessment.subproxy.delete');
    Route::post('/subproxy/rumus/save', 'AssessmentController@AddRumus')->name('assessment.subproxy.rumus.add');
    Route::get('/subproxy/rumus/get/{proxy_id}', 'AssessmentController@GetRumus')->name('assessment.subproxy.rumus.get');


});

Route::group(['prefix' => 'calculate','middleware' => 'auth'], function () {
    Route::get('/employee/{employee_id}', 'CalculateController@index')->name('calculate.index');
    Route::post('/subproxy', 'CalculateController@CalculateSubproxy')->name('calculate.subproxy');
});

Route::group(['prefix' => 'recap','middleware' => 'auth'], function () {
    Route::get('/', 'RecapController@index')->name('recap.index');
    Route::post('/save', 'RecapController@store')->name('recap.store');
    Route::get('/get-report/{from}/{to}/{employee_id}', 'RecapController@report')->name('recap.report');
});

app/Satuan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Satuan extends Model
{
    protected $fillable = [
        'name','user_id','status'
    ];

    public function scopeUserLogin($query)
    {
        return $query->where('user_id', user_login()->id);
    }

    public function scopeStatusActived($query)
    {
        return $query->where('status',1);
    }
}

app/Http/Controllers/SatuanController.php
<?php

namespace App\Http\Controllers;

use App\Satuan;
use App\Http\Requests\Satuan\SatuanRequest;


class SatuanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $satuans = Satuan::userLogin()->statusActived()->get();
        return view('admin.satuan.index', compact('satuans'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.satuan.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SatuanRequest $request)
    {
        try {
            $position = Satuan::create(['name' => $request->name, 'user_id' => user_login()->id, 'status' => 1]);
            
            createSession('success','Data berhasil disimpan ...');
            return redirect(route('satuan.index'));
        } catch (\Throwable $th) {
            createSession('danger',$th->getMessage());
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $satuan = Satuan::findOrFail($id);
        return view('admin.satuan.form', compact('satuan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SatuanRequest $request, $id)
    {
        try {
            $satuan = Satuan::findOrFail($id);
            $satuan->name = $request->name;
            $satuan->user_id = user_login()->id;
            $satuan->save();

            createSession('success','Data berhasil disimpan ...');
            return redirect(route('satuan.index'));
        } catch (\Throwable $th) {
            createSession('danger',$th->getMessage());
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $satuan = Satuan::findOrFail($id);
            $satuan->status = 0;
            $satuan->save();

            createSession('success','Data berhasil dihapus ...');
            return redirect(route('satuan.index'));
        } catch (\Throwable $th) {
            createSession('danger',$th->getMessage());
            return back();
        }
    }
}

resources/views/admin/satuan/css.blade.php
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('assets') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="{{ asset('assets') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <link rel="stylesheet" href="{{ asset('assets') }}/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

resources/views/admin/satuan/form.blade.php
@extends('layouts.main_app')
@push('css')
@include('admin.satuan.css')
@endpush
@push('script')
@include('admin.satuan.script')
@endpush
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Satuan</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Master Data</a></li>
                    <li class="breadcrumb-item active">Satuan</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Form Satuan</h3>
                    </div>
                    @php
                        $url = route('satuan.store');
                        if (!empty($satuan)) {
                            $url = route('satuan.update',$satuan->id);
                        }
                    @endphp
                    <form action="{{ $url }}" method="POST">
                        @csrf
                        @if (!empty($satuan))
                            @method('PUT')
                        @endif
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">Nama Satuan</label>
                                <input type="text" class="form-control" id="name" placeholder="Masukkan name" name="name" required value="{{ @$satuan->name }}">
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">SAVE</button>
                        </div>
                    </form>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

resources/views/admin/satuan/get-indicator.blade.php
@extends('layouts.main_app')
@push('css')
@include('admin.position.css')
@endpush
@push('script')
@include('admin.position.script')
@endpush
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Indikator</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Master Data</a></li>
                    <li class="breadcrumb-item">Jabatan</li>
                    <li class="breadcrumb-item active">Indikator</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                       <h4>{{ $position->name }}</h4>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Nama Indikator</th>
                                    <th>Bobot</th>
                                    <th>Deskripsi</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($indicators as $indicator)
                                <tr>
                                    <td>{{ $indicator->name }}</td>
                                    <td>{{ $indicator->bobot }} %</td>
                                    <td>{{ $indicator->description }}</td>
                                    <td>
                                        <form action="{{ route('position.deleteIndicator', $indicator->id) }}" method="POST">
                                        {{ csrf_field() }} @method('DELETE')
                                        <button type="submit" onclick="return confirm('Apakah Anda Yakin ?')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="4">Data not found</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                        <br><br>
                        <h4>Tabel List Indikator</h4>
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Nama Indikator</th>
                                    <th>Deskripsi</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($otherIndicators as $otherIndicator)
                                <tr>
                                    <td>{{ $otherIndicator->name }}</td>
                                    <td>{{ $otherIndicator->description }}</td>
                                    <td>
                                        <button id="add-indicator-btn" type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modal-add-indicator" data-id="{{ $otherIndicator->id }}">
                                            <i class="fa fa-plus"></i>
                                          </button>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="3">Data not found</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                        
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->

{{--  include Modal  --}}
@include('admin.position.modal-add-indicator')
@endsection

resources/views/admin/satuan/index.blade.php
@extends('layouts.main_app')
@push('css')
@include('admin.satuan.css')
@endpush
@push('script')
@include('admin.satuan.script')
@endpush
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Satuan</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Master Data</a></li>
                    <li class="breadcrumb-item active">Satuan</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="text-right">
                            <a href="{{ route('satuan.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah Satuan</a>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Nama Satuan</th>
                                    {{--  <th>Indikator</th>  --}}
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($satuans as $satuan)
                                    <tr>
                                        <td>{{ $satuan->name }}</td>
                                        {{--  <td>
                                            <ul>
                                                @foreach ($satuan->indicators as $indicator)
                                                    <li>{{ $indicator->name }} ({{ $indicator->bobot }} %)</li>
                                                @endforeach
                                            </ul>
                                        </td>  --}}
                                        <td> 
                                            <table>
                                                <tr>
                                                    <td><a href="{{ route('satuan.edit',$satuan->id) }}" class="btn btn-warning btn-sm mr-1"><i class="fa fa-edit"></i></a></td>
                                                    <td><form action="{{ route('satuan.destroy', $satuan->id) }}" method="POST">@csrf @method('DELETE')  <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('apakah anda yakin ?')"><i class="fa fa-trash"></i></button> </form></td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="3">Data no found</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

resources/views/admin/satuan/modal-add-indicator.blade.php
<div class="modal fade" id="modal-add-indicator">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="{{ route('position.addIndicator.post') }}" method="POST">
                {{ csrf_field() }}
                <div class="modal-header">
                    <h4 class="modal-title">Tambah Indicator</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <input type="hidden" name="indicator_id" id="indicator_id_add">
                        <input type="hidden" name="position_id" id="position_id_add" value="{{ $position->id }}">
                        <label for="bobot">Bobot Indicator</label>
                        <div class="input-group mb-3">
                            <input type="number" class="form-control" min="0" max="100" name="bobot" required>
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fa fa-percent"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">SAVE</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/admin/satuan/script.blade.php
<!-- DataTables  & Plugins -->
<script src="{{ asset('assets') }}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="{{ asset('assets') }}/plugins/jszip/jszip.min.js"></script>
<script src="{{ asset('assets') }}/plugins/pdfmake/pdfmake.min.js"></script>
<script src="{{ asset('assets') }}/plugins/pdfmake/vfs_fonts.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

<script>
    $(function () {
        $("#example1").DataTable({
            "responsive": true, "lengthChange": false, "autoWidth": true,
            "buttons": ["csv", "excel", "pdf", "print"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    });

    $('#add-indicator-btn').on('click', function (e) {
        $('#indicator_id_add').val($(this).data("id"));
    })
</script>