routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('dashboard');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

Route::group(['prefix' => 'master-data'], function () {
    Route::resource('/employee', 'EmployeeController')->middleware('auth');

    //position route
    Route::resource('/position', 'PositionController')->middleware('auth');
    Route::get('/position/get-indicator/{position_id}', 'PositionController@GetIndicator')->middleware('auth')->name('position.add_indicator');
    Route::post('/position/add-indicator', 'PositionController@AddIndicator')->middleware('auth')->name('position.addIndicator.post');
    Route::delete('position/delete-indicator/{indicator_id}', 'PositionController@DeleteIndicator')->middleware('auth')->name('position.deleteIndicator');
    Route::get('/position/{position_id}/params_data', 'AssessmentController@IndexParamsData')->name('position.indexparamsdata');

    Route::resource('/indicator', 'IndicatorController')->middleware('auth');
    Route::get('/indicator/get-proxy/{indicator_id}', 'IndicatorController@GetProxy')->middleware('auth')->name('indicator.add_proxy');
    Route::post('/indicator/add-proxy/', 'IndicatorController@AddProxy')->middleware('auth')->name('indicator.addProxy.post');
    Route::delete('indicator/delete-proxy/{proxy_id}', 'IndicatorController@DeleteProxy')->middleware('auth')->name('indicator.deleteProxy');

    // Route::resource('/job', 'JobController')->middleware('auth');
    Route::resource('/proxy', 'ProxyController')->middleware('auth');
    Route::resource('/subproxy', 'SubProxyController')->middleware('auth');

    //satuan route
    Route::resource('/satuan', 'SatuanController')->middleware('auth');


});

Route::group(['prefix' => 'assessment','middleware' => 'auth'], function () {
    Route::get('/employee', 'AssessmentController@Employee')->name('assessment.employee');
    //indicator
    Route::post('/indicator/save', 'AssessmentController@IndicatorSave')->name('assessment.indicator.save');
    Route::post('/indicator/update/{indicator_id}', 'AssessmentController@IndicatorUpdate')->name('assessment.indicator.update');
    Route::get('/indicator/get/{indicator_id}', 'AssessmentController@GetIndicator')->name('assessment.indicator.get');
    Route::get('/indicator/delete/{indicator_id}','AssessmentController@IndicatorDelete')->name('assessment.indicator.delete');

    //proxy
    Route::post('/proxy/save', 'AssessmentController@ProxySave')->name('assessment.proxy.save');
    Route::post('/proxy/update/{proxy_id}', 'AssessmentController@ProxyUpdate')->name('assessment.proxy.update');
    Route::get('/proxy/get/{proxy_id}', 'AssessmentController@GetProxy')->name('assessment.proxy.get');
    Route::get('/proxy/delete/{proxy_id}','AssessmentController@ProxyDelete')->name('assessment.proxy.delete');

    //subproxy
    Route::post('/subproxy/save', 'AssessmentController@SubProxySave')->name('assessment.subproxy.save');
    Route::post('/subproxy/update/{subproxy_id}', 'AssessmentController@SubProxyUpdate')->name('assessment.subproxy.update');
    Route::get('/subproxy/get/{subproxy_id}', 'AssessmentController@GetSubProxy')->name('assessment.subproxy.get');
    Route::get('/subproxy/delete/{subproxy_id}','AssessmentController@SubProxyDelete')->name('assessment.subproxy.delete');
    Route::post('/subproxy/rumus/save', 'AssessmentController@AddRumus')->name('assessment.subproxy.rumus.add');
    Route::get('/subproxy/rumus/get/{proxy_id}', 'AssessmentController@GetRumus')->name('assessment.subproxy.rumus.get');


});

Route::group(['prefix' => 'calculate','middleware' => 'auth'], function () {
    Route::get('/employee/{employee_id}', 'CalculateController@index')->name('calculate.index');
    Route::post('/subproxy', 'CalculateController@CalculateSubproxy')->name('calculate.subproxy');
});

Route::group(['prefix' => 'recap','middleware' => 'auth'], function () {
    Route::get('/', 'RecapController@index')->name('recap.index');
    Route::post('/save', 'RecapController@store')->name('recap.store');
    Route::get('/get-report/{from}/{to}/{employee_id}', 'RecapController@report')->name('recap.report');
});

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = [
        'kode','nama','jenis_kelamin','email','no_telephone','position_id','user_id'
    ];

    public function position()
    {
        return $this->hasOne('App\Position', 'id','position_id');
    }

    public function scopeUserLogin($query)
    {
        return $query->where('user_id', user_login()->id);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\employee\EmployeeRequest;
use App\Employee;
use App\Position;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::userLogin()->get();
        return view('admin.employee.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $positions = Position::userLogin()->get();
        return view('admin.employee.form', compact('positions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        try {
            $employee = Employee::create([
                'kode' => $request->kode,
                'nama' => $request->nama,
                'jenis_kelamin' => $request->jenis_kelamin,
                'email' => $request->email,
                'no_telephone' => $request->no_telephone,
                'position_id' => $request->position_id,
                'user_id' => user_login()->id,
            ]);

            createSession('success','Data berhasil disimpan ...');
            return redirect(route('employee.index'));
        } catch (\Throwable $th) {
            createSession('danger',$th->getMessage());
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Employee::findOrFail($id);
        $positions = Position::userLogin()->get();
        return view('admin.employee.form', compact('employee','positions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeRequest $request, $id)
    {
        try {
            $employee = Employee::findOrFail($id);
            $employee->kode = $request->kode;
            $employee->nama = $request->nama;
            $employee->jenis_kelamin = $request->jenis_kelamin;
            $employee->email = $request->email;
            $employee->no_telephone = $request->no_telephone;
            $employee->user_id = user_login()->id;
            $employee->save();

            createSession('success','Data berhasil disimpan ...');
            return redirect(route('employee.index'));
        } catch (\Throwable $th) {
            createSession('danger',$th->getMessage());
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $employee = Employee::destroy($id);
            
            createSession('success','Data berhasil dihapus ...');
            return redirect(route('employee.index'));
        } catch (\Throwable $th) {
            createSession('danger',$th->getMessage());
            return back();
        }
    }
}

resources/views/admin/employee/css.blade.php
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('assets') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="{{ asset('assets') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <link rel="stylesheet" href="{{ asset('assets') }}/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

resources/views/admin/employee/form.blade.php
@extends('layouts.main_app')
@push('css')
@include('admin.employee.css')
@endpush
@push('script')
@include('admin.employee.script')
@endpush
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Pegawai</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Master Data</a></li>
                    <li class="breadcrumb-item active">Pegawai</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Form Pegawai</h3>
                    </div>
                    @php
                        $url = route('employee.store');
                        if (!empty($employee)) {
                            $url = route('employee.update',$employee->id);
                        }
                    @endphp
                    <form action="{{ $url }}" method="POST">
                        @csrf
                        @if (!empty($employee))
                            @method('PUT')
                        @endif
                        <div class="card-body">
                            <div class="form-group">
                                <label for="kode">Kode Pegawai</label>
                                <input type="number" class="form-control" id="kode" placeholder="Masukkan kode" name="kode" value="{{ @$employee->kode }}" required>
                            </div>
                            <div class="form-group">
                                <label for="nama">Nama Pegawai</label>
                                <input type="text" class="form-control" id="nama" placeholder="Masukkan nama" name="nama" required value="{{ @$employee->nama }}">
                            </div>
                            <div class="form-group">
                                <label for="jenis_kelamin">Jenis Kelamin</label><br>
                                <input type="radio" name="jenis_kelamin" id="jenis_kelamin" value="Pria" @if (@$employee->jenis_kelamin == 'Pria') checked @endif> Pria
                                <input type="radio" name="jenis_kelamin" id="jenis_kelamin" value="Wanita"  @if (@$employee->jenis_kelamin == 'Wanita') checked @endif> Wanita
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control" id="email" placeholder="Masukkan email" name="email" required value="{{ @$employee->email }}">
                            </div>
                            <div class="form-group">
                                <label for="no_telephone">No. Telephone</label>
                                <input type="number" class="form-control" id="no_telephone" placeholder="Masukkan no_telephone" name="no_telephone" required value="{{ @$employee->no_telephone }}">
                            </div>
                            <div class="form-group">
                                <label for="position_id">Jabatan</label>
                                <select name="position_id" id="position_id" class="form-control" required>
                                    <option value="">-- jabatan --</option>
                                    @forelse ($positions as $position)
                                       <option value="{{ $position->id }}" @if (@$position->id == @$employee->position_id) selected @endif>{{ $position->name }}</option> 
                                    @empty
                                    @endforelse
                                </select>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">SAVE</button>
                        </div>
                    </form>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

resources/views/admin/employee/index.blade.php
@extends('layouts.main_app')
@push('css')
@include('admin.employee.css')
@endpush
@push('script')
@include('admin.employee.script')
@endpush
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Pegawai</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Master Data</a></li>
                    <li class="breadcrumb-item active">Pegawai</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="text-right">
                            <a href="{{ route('employee.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah Pegawai</a>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Kode</th>
                                    <th>Nama</th>
                                    <th>Jenis Kelamin</th>
                                    <th>Email</th>
                                    <th>No. Telephone</th>
                                    <th>Jabatan</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($employees as $employee)
                                    <tr>
                                        <td>{{ $employee->kode }}</td>
                                        <td>{{ $employee->nama }}</td>
                                        <td>{{ $employee->jenis_kelamin }}</td>
                                        <td>{{ $employee->email }}</td>
                                        <td>{{ $employee->no_telephone }}</td>
                                        <td>{{ $employee->position->name }}</td>
                                        <td>
                                            <div class="row">
                                                <a href="{{ route('employee.edit',$employee->id) }}" class="btn btn-warning btn-sm mr-1"><i class="fa fa-edit"></i></a>
                                                <form action="{{ route('employee.destroy', $employee->id) }}" method="POST">@csrf @method('DELETE')  <button class="btn btn-danger btn-sm" type="submit" onclick="return confirm('apakah anda yakin ?')"><i class="fa fa-trash"></i></button> </form>
                                            </div>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="7">Data not found</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

resources/views/admin/employee/script.blade.php
<!-- DataTables  & Plugins -->
<script src="{{ asset('assets') }}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="{{ asset('assets') }}/plugins/jszip/jszip.min.js"></script>
<script src="{{ asset('assets') }}/plugins/pdfmake/pdfmake.min.js"></script>
<script src="{{ asset('assets') }}/plugins/pdfmake/vfs_fonts.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="{{ asset('assets') }}/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

<script>
    $(function () {
        $("#example1").DataTable({
            "responsive": true, "lengthChange": false, "autoWidth": false,
            "buttons": ["csv", "excel", "pdf", "print"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    });
</script>